### ISSUE TITLE
Testing new twain

### ISSUE THREAD

**Issue by keithculotta** [miyako/4d-plugin-twain#1]
Hello,

This is a very timely addition.  Recently a customer requested the ability to scan directly into their application.  
It's probably premature to try, but I opened "TWAIN.4dbase" in v16.3  217792.
After running this line: TWAIN SCANNERS LIST ($scanners), $scanners remained size zero.
The app "Preview" does list scaners in its File menu.

MacBook Pro (Retina, 15-inch, Early 2013) - macOS 10.13.1

Thanks,
Keith

**Comment by miyako** [comment]
very few vendors publish TWAIN drivers for Mac today. your device is probably ICA. you should try https://github.com/miyako/4d-plugin-ica instead.
